
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CLOSE LISTEN OPEN PATHexpression : OPEN PATHexpression : CLOSE PATHexpression : OPEN PATH AND PATHexpression : CLOSE PATH AND PATHexpression : LISTEN'
    
_lr_action_items = {'OPEN':([0,],[2,]),'CLOSE':([0,],[3,]),'LISTEN':([0,],[4,]),'$end':([1,4,5,6,9,10,],[0,-5,-1,-2,-3,-4,]),'PATH':([2,3,7,8,],[5,6,9,10,]),'AND':([5,6,],[7,8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> OPEN PATH','expression',2,'p_statement_open','consolePL.py',56),
  ('expression -> CLOSE PATH','expression',2,'p_statement_close','consolePL.py',61),
  ('expression -> OPEN PATH AND PATH','expression',4,'p_statement_open_m','consolePL.py',67),
  ('expression -> CLOSE PATH AND PATH','expression',4,'p_statement_close_m','consolePL.py',73),
  ('expression -> LISTEN','expression',1,'p_statement_listen','consolePL.py',80),
]
